# Generated by Django 5.1.3 on 2024-12-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0002_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
